let jobPost = [
    {
        jobId: Date.now(),
        companyName: "Mobile First Corp",
        jobPosition: "React Native Developer",
        location: "Remote",
        jobType: "Full-time",
        salaryRange: "7000 - 9000 USD",
        status: "Open",
        jobDescription: "Build cross-platform mobile applications using React Native. Work on products used by millions of users worldwide.",
    },
    {
        jobId: Date.now() + 1,
        companyName: "TechNova Solutions",
        jobPosition: "Frontend Developer",
        location: "Dhaka",
        jobType: "Full-time",
        salaryRange: "5000 - 6500 USD",
        status: "Open",
        jobDescription: "Develop responsive web applications using React and Tailwind CSS.",
    },
    {
        jobId: Date.now() + 2,
        companyName: "CloudSync Ltd",
        jobPosition: "Backend Developer",
        location: "Remote",
        jobType: "Full-time",
        salaryRange: "6500 - 8000 USD",
        status: "Open",
        jobDescription: "Design and maintain scalable backend systems using Node.js and Express.",
    },
    {
        jobId: Date.now() + 3,
        companyName: "PixelCraft Studio",
        jobPosition: "UI/UX Designer",
        location: "Chittagong",
        jobType: "Part-time",
        salaryRange: "3000 - 4500 USD",
        status: "Open",
        jobDescription: "Create modern and user-friendly UI designs for web and mobile applications.",
    },
    {
        jobId: Date.now() + 4,
        companyName: "DataNest Analytics",
        jobPosition: "Data Analyst",
        location: "Remote",
        jobType: "Contract",
        salaryRange: "6000 - 7500 USD",
        status: "Open",
        jobDescription: "Analyze large datasets and generate actionable insights for business growth.",
    },
    {
        jobId: Date.now() + 5,
        companyName: "SecureNet Systems",
        jobPosition: "Cyber Security Specialist",
        location: "Dhaka",
        jobType: "Full-time",
        salaryRange: "8000 - 9500 USD",
        status: "Open",
        jobDescription: "Monitor and secure company infrastructure against cyber threats.",
    },
    {
        jobId: Date.now() + 6,
        companyName: "AI Vision Labs",
        jobPosition: "Machine Learning Engineer",
        location: "Remote",
        jobType: "Full-time",
        salaryRange: "9000 - 12000 USD",
        status: "Open",
        jobDescription: "Develop and deploy machine learning models for real-world AI applications.",
    },
    {
        jobId: Date.now() + 7,
        companyName: "DevOpsify",
        jobPosition: "DevOps Engineer",
        location: "Khulna",
        jobType: "Full-time",
        salaryRange: "7500 - 9000 USD",
        status: "Open",
        jobDescription: "Automate deployment pipelines and manage cloud infrastructure.",
    }
];